name: CICD Test

# Trigger the workflow on any push to the main branch or pull request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Check out the code from the repository and CML (Continuous Machine Learning) Commands
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: iterative/setup-cml@v1

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Train Model
      - name: Train Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python 'tests/test_model.py'
          echo "RF and LR Model Score" >report.md
          cat scores.txt
          echo "Confusion Matrix & Feature Importance">report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md
          cat report.md report1.md >> combined_file.md
          cml comment create combined_file.md
          
      # Step 6: Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Model Reports and Outputs
          path: |
            combined_file.md
            ConfusionMatrix.png
            FeatureImportance.png
            scores.txt
            
      # Step 6: Commit Files
      - name: Commit Results
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add combined_file.md ConfusionMatrix.png FeatureImportance.png scores.txt
          git commit -m "Add model reports and outputs"
          git push
