name: CICD Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Train Model
      - name: Train Model
        run: |
          python 'tests/train_model.py'
          echo "RF and LR Model Score" >report.md
          cat scores.txt
          
          echo "Confusion Matrix & Feature Importance">report1.md
          echo '|[](./ConfusionMatrix.png "ConfusionMatrix")' >> report1.md
          echo '|[](./FeatureImportance.png "FeatureImportance")' >> report1.md
     
          cat report.md report1.md >> combined_file.md

      # Step 5: Setup Node.js for CML
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # Step 6: Install and Use CML
      - name: Install CML
        run: |
          npm install -g @dvcorg/cml
      - name: Create CML Comment
        run: |
          cml comment create combined_file.md

      # Step 7: Run tests
      - name: Test with pytest
        run: pytest
